### PR TITLE
major editing of Testing and Review section

### PR DESCRIPTION
**Pull request by kcranston**
I've done a fairly major rearrangement of section 10 (Testing and Code Review). @danielskatz and @tclune - let me know what you think. Still more to do, but wanted an interim review.

### CODE REVIEW

**Comment by danielskatz** [comment]
In general, this looks quite good to me.

I don't want to add the Hook and Kelly papers to the list of papers discussed, however, since they are not WSSSPE2 papers that everyone read before the meeting, but rather, papers introduced during the session.  Can you just refer to them in the text without having them in the list of (WSSSPE2) papers?

Dan

**Comment by kcranston** [comment]
Ah, I didn't understand the semantics of "Papers Discussed". Will do.

**Comment by kcranston** [comment]
Done.

**Comment by danielskatz** [comment]
Good, thanks! - feel free to do more as you think is needed - let me know when you are done, please

**Pull request merged**
